# Generated by Django 6.0.5 on 2026-07-11 06:26

import apps.resume.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=apps.resume.utils.resume_upload_path),
        ),
    ]
