# Generated by Django 6.0.5 on 2026-07-11 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='missing_keywords',
            new_name='missing_skills',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
