# Generated by Django 6.0.5 on 2026-07-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resumeanalysis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analyzed_at',
        ),
    ]
